function y = Trimshamsa(x)
# usage: Trimshamsha (x)
# x is a structure which has two fields: longitude Rashi
# Longitude position to be mentioned in degrees
# This function calculates the trimshamsa of the planet

%Trimshamsa table in an array with Degrees x Rashi dimension
trimshamsha_table = {...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...

"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...

"Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi";...
"Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi";...

"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...

"Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi";...
"Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi";...

"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...

"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
};

y = trimshamsha_table(x(1), x(2));
endfunction
