# usage: Trimshamsha (Longitude, Rashiname)
# Rashi name can be given as Ar, Ta...
# Longitude position to be mentioned in integer or decimal format
# This function calculates the trimshamsa of the planet
# Example Usage: 
# If Rashiname = Ar and Longitude = 15.44
# y = Trimshamsa ("15.44","Ar");

function y = Trimshamsa(Longitude, Rashiname)

%Trimshamsa table in an array with Degrees x Rashi dimension

trimshamsha_table = {...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...
"Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta","Ar","Ta";...

"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...
"Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi","Aq","Vi";...

"Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi";...
"Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi","Sg","Vi";...

"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...
"Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi","Sg","Pi";...

"Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi";...
"Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi","Ge","Pi";...

"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...
"Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp","Ge","Cp";...

"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
"Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc","Li","Sc";...
};

RasiNumber = Find_Rasi_number (Rashiname);
Rasi = str2num(RasiNumber);

% The following function converts the Longitude argument string to number 
% and takes the ceiling value to support decimals

LongiField = ceil (str2num(Longitude));

y = trimshamsha_table(LongiField, Rasi);
endfunction
